app_code: framework
app_name: 开发框架
author: 蓝鲸智云
category: 开发工具
introduction: “开发框架”是蓝鲸智云团队为开发者提供的示例代码，基于此框架，开发者可以快速上手，利用蓝鲸智云集成平台（PaaS）提供的调度引擎、公共组件等模块，构建低成本、免运维的支撑工具和运营系统。
version: 1.0.1
language: python
is_use_celery: True
desktop:
    width: 1200
    height: 720
    is_max: False
date: 2017-09-08 12:00:00
