# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_user', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_user', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_application.Config')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_application.Service')),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_application.Module'),
        ),
    ]
