# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0004_project_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='comment',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
